const fs = require('fs');
const path = require('path');

const COURSES_DIR = path.join(__dirname, 'contenu_cours_par_langue');
const UNIT0_FILE = path.join(__dirname, 'src', 'data', 'reference', 'units', 'unit0.ts');

const TARGET_EXERCISES = 5;
const REQUIRED_LESSONS = 10;

const LANGUAGES = [
    'wolof', 'serer', 'diola', 'pulaar', 'soninke', 'bambara',
    'mandinka', 'manjak', 'balante', 'mankagne', 'bainouk', 'menik', 'hassaniya'
];

function extractUnit0FromMarkdown(content) {
    const match = content.match(/##\s*Unité\s*0\s*([\s\S]*?)(?:##\s*Unité\s*1|$)/i);
    if (!match) return null;
    return match[1];
}

function parseMarkdownListTokens(sectionText) {
    const lines = sectionText.split('\n');
    const sections = [];
    let currentTitle = null;
    let currentItems = [];

    for (let line of lines) {
        line = line.trim();
        if (line.startsWith('###')) {
            if (currentTitle) {
                sections.push({ title: currentTitle, items: currentItems });
            }
            currentTitle = line.replace(/^###\s*/, '').trim();
            currentItems = [];
        } else if (line.startsWith('-') || line.startsWith('*')) {
            const parts = line.replace(/^[-*]\s*/, '').split(':').map(p => p.trim());
            if (parts.length >= 2) {
                let term = parts[0].replace(/\*\*/g, '').trim();
                let trans = parts.slice(1).join(':').trim();
                trans = trans.replace(/^\*\*(.*?)\*\*/, '$1');
                currentItems.push({ term, trans });
            }
        }
    }
    if (currentTitle) {
        sections.push({ title: currentTitle, items: currentItems });
    }
    return sections;
}

function generateUnit0Data() {
    const finalData = {};
    const fallbackUnit0Str = fs.readFileSync(UNIT0_FILE, 'utf8');
    let fallbackData = {};
    const fallbackMatch = fallbackUnit0Str.match(/export\s+const\s+UNIT_0_STATIC_DATA.*?=\s*(\{[\s\S]*\}\s*);/m);
    if (fallbackMatch) {
         try {
             const tempFn = new Function('return ' + fallbackMatch[1]);
             fallbackData = tempFn();
         } catch(e) {
             console.error("Failed to parse existing unit0 fallback", e);
         }
    }

    const mdFiles = fs.readdirSync(COURSES_DIR).filter(f => f.endsWith('.md'));

    for (const lang of LANGUAGES) {
        finalData[lang] = {};
        let mdFile = mdFiles.find(f => f.toLowerCase().startsWith(lang.toLowerCase().replace('-', '_')));
        let sections = [];

        if (mdFile) {
            const content = fs.readFileSync(path.join(COURSES_DIR, mdFile), 'utf8');
            const unit0Text = extractUnit0FromMarkdown(content);
            if (unit0Text) {
                sections = parseMarkdownListTokens(unit0Text);
            }
        }

        let lessons = [];

        if (sections.length === 0 && fallbackData[lang]) {
            for (const [title, items] of Object.entries(fallbackData[lang])) {
                sections.push({ title, items });
            }
        }

        if (sections.length === 0) continue;

        for (const sec of sections) {
            const { title, items } = sec;
            if (items.length === 0) continue;

            const numChunks = Math.ceil(items.length / TARGET_EXERCISES);
            for (let i = 0; i < numChunks; i++) {
                let chunk = items.slice(i * TARGET_EXERCISES, (i + 1) * TARGET_EXERCISES);
                
                if (chunk.length < TARGET_EXERCISES && chunk.length > 0) {
                    while (chunk.length < TARGET_EXERCISES) {
                        const needed = TARGET_EXERCISES - chunk.length;
                        chunk = chunk.concat(chunk.slice(0, needed));
                    }
                }

                let chunkTitle = numChunks === 1 ? title : `${title} (Partie ${i + 1})`;
                lessons.push({ title: chunkTitle, items: chunk });
            }
        }

        if (lessons.length > 0) {
            let originalCount = lessons.length;
            let counter = 1;
            while (lessons.length < REQUIRED_LESSONS) {
                const source = lessons[(counter - 1) % originalCount];
                lessons.push({
                    title: `${source.title} (Suite ${Math.ceil(counter / originalCount)})`,
                    items: [...source.items]
                });
                counter++;
            }
        }

        lessons = lessons.slice(0, REQUIRED_LESSONS);

        for (const l of lessons) {
            finalData[lang][l.title] = l.items;
        }
    }
    return finalData;
}

const newData = generateUnit0Data();

const outputTs = `// AUTOGENERATED FILE - Do not manually edit if refresh_unit0.js is in use.
import { ExerciseType } from '../../../types';

export const UNIT_0_STATIC_DATA: Record<string, Record<string, { term: string, trans: string, context?: string }[]>> = 
${JSON.stringify(newData, null, 4)};
`;

fs.writeFileSync(UNIT0_FILE, outputTs, 'utf8');
console.log('Successfully updated unit0.ts with exact 5 keys and 5 items per lesson for all languages.');
