// AUTOGENERATED FILE - Do not manually edit if refresh_unit0.js is in use.
import { ExerciseType } from '../../../types';

export const UNIT_0_STATIC_DATA: Record<string, Record<string, { term: string, trans: string, context?: string }[]>> = 
{
    "wolof": {
        "Alphabet : Les Voyelles": [
            { "term": "a", "trans": "ba (le / la)" },
            { "term": "e", "trans": "fecc (danser)" },
            { "term": "i", "trans": "ci (dans / avec)" },
            { "term": "o", "trans": "lool (beaucoup)" },
            { "term": "u", "trans": "mu (il / elle)" }
        ],
        "Alphabet : Consonnes (1)": [
            { "term": "b", "trans": "benn (un)" },
            { "term": "c", "trans": "ca (préposition / article)" },
            { "term": "d", "trans": "daagu (marcher avec fierté)" },
            { "term": "f", "trans": "fecc (danser)" },
            { "term": "g", "trans": "gawar (cavalier)" }
        ],
        "Alphabet : Consonnes (2)": [
            { "term": "j", "trans": "jóg (se lever)" },
            { "term": "l", "trans": "lool (beaucoup)" },
            { "term": "m", "trans": "mu (il / elle)" },
            { "term": "b", "trans": "buur (roi)" },
            { "term": "d", "trans": "digg (milieu)" }
        ],
        "Alphabet : Consonnes (3)": [
            { "term": "n", "trans": "na (particule d'affirmation)" },
            { "term": "ñ", "trans": "ñaari (deux)" },
            { "term": "p", "trans": "pettaaw (cauris)" },
            { "term": "t", "trans": "taxaw (s'arrêter / se tenir debout)" },
            { "term": "w", "trans": "way (chanter)" }
        ],
        "Alphabet : Consonnes (4)": [
            { "term": "x", "trans": "xumb (animé / bruyant)" },
            { "term": "y", "trans": "yaa (tu / toi)" },
            { "term": "n", "trans": "ngan (invité)" },
            { "term": "x", "trans": "xar (mouton)" },
            { "term": "w", "trans": "waajal (préparer)" }
        ],
        "Les Accents : é, ó, à, ë": [
            { "term": "é", "trans": "géew (cercle / arène)" },
            { "term": "ó", "trans": "jóg (se lever)" },
            { "term": "à", "trans": "ànd (accompagner / avec)" },
            { "term": "ë", "trans": "fuddën (teindre au henné)" },
            { "term": "à", "trans": "tànk (pied)" }
        ],
        "Le redoublement des Voyelles": [
            { "term": "aa", "trans": "daagu (marcher fièrement)" },
            { "term": "ee", "trans": "téeméer (cent)" },
            { "term": "ii", "trans": "juróomi (cinq)" },
            { "term": "oo", "trans": "lool (beaucoup)" },
            { "term": "uu", "trans": "buur (roi)" }
        ],
        "Le redoublement des Consonnes": [
            { "term": "dd", "trans": "fuddën (henné)" },
            { "term": "gg", "trans": "dégg (entendre / comprendre)" },
            { "term": "pp", "trans": "ëpp (plus que)" },
            { "term": "tt", "trans": "pettaaw (cauris)" },
            { "term": "nn", "trans": "benn (un)" }
        ],
        "Les Prénasales (mb, nd, ng)": [
            { "term": "mb", "trans": "xumb (animé)" },
            { "term": "nd", "trans": "ànd (accompagner)" },
            { "term": "ng", "trans": "ngan (invité)" },
            { "term": "ng", "trans": "gàngoor (groupe / troupe)" },
            { "term": "nd", "trans": "Penda (Prénom)" }
        ],
        "Synthèse : Phrases du texte": [
            { "term": "Penda jóg taxaw ca digg géew ba.", "trans": "Penda s'est levée et s'est tenue au milieu du cercle." },
            { "term": "Dañoo fuddën ay tànkam ba mu ñuul.", "trans": "Ils ont teinté ses pieds au henné jusqu'à ce qu'ils soient noirs." },
            { "term": "Ñaari pettaaw di lang ci jë ba.", "trans": "Deux cauris étaient suspendus à son front." },
            { "term": "Benn buur dégg taaru Penda.", "trans": "Un roi a entendu parler de la beauté de Penda." },
            { "term": "Mu waajal ngan.", "trans": "Il a préparé une réception (pour l'invitée)." }
        ],
        "Pronoms Personnels (Tonic) (Partie 1)": [
            {
                "term": "man",
                "trans": "moi"
            },
            {
                "term": "yaw",
                "trans": "toi"
            },
            {
                "term": "moom",
                "trans": "lui / elle"
            },
            {
                "term": "ñun",
                "trans": "nous"
            },
            {
                "term": "yeen",
                "trans": "vous"
            }
        ],
        "Pronoms Personnels (Tonic) (Partie 2)": [
            {
                "term": "ñoom",
                "trans": "eux / elles"
            },
            {
                "term": "ñoom",
                "trans": "eux / elles"
            },
            {
                "term": "ñoom",
                "trans": "eux / elles"
            },
            {
                "term": "ñoom",
                "trans": "eux / elles"
            },
            {
                "term": "ñoom",
                "trans": "eux / elles"
            }
        ],
        "Syntaxe : Focus Sujet (Partie 1)": [
            {
                "term": "maa",
                "trans": "c'est moi qui... (1S)"
            },
            {
                "term": "yaa",
                "trans": "c'est toi qui... (2S)"
            },
            {
                "term": "moo",
                "trans": "c'est lui/elle qui... (3S)"
            },
            {
                "term": "noo",
                "trans": "c'est nous qui... (1P)"
            },
            {
                "term": "yeena",
                "trans": "c'est vous qui... (2P)"
            }
        ],
        "Syntaxe : Focus Sujet (Partie 2)": [
            {
                "term": "ñoo",
                "trans": "ce sont eux qui... (3P)"
            },
            {
                "term": "ñoo",
                "trans": "ce sont eux qui... (3P)"
            },
            {
                "term": "ñoo",
                "trans": "ce sont eux qui... (3P)"
            },
            {
                "term": "ñoo",
                "trans": "ce sont eux qui... (3P)"
            },
            {
                "term": "ñoo",
                "trans": "ce sont eux qui... (3P)"
            }
        ]
    },
    "serer": {
        "Alphabet et Sons (Partie 1)": [
            {
                "term": "A",
                "trans": "comme a-ndat (la hache)"
            },
            {
                "term": "B",
                "trans": "comme baabo (papa)"
            },
            {
                "term": "Ɓ",
                "trans": "comme ɓasil (prier) (*Injective (U+0181).*)"
            },
            {
                "term": "C",
                "trans": "comme col (la colère)"
            },
            {
                "term": "Ƈ",
                "trans": "comme ƈaar (regarder) (*Injective (U+0188).*)"
            }
        ],
        "Alphabet et Sons (Partie 2)": [
            {
                "term": "D",
                "trans": "comme dak (la tête)"
            },
            {
                "term": "Ɗ",
                "trans": "comme ɗaba (biner) (*Injective (U+0257).*)"
            },
            {
                "term": "E",
                "trans": "comme ele (demain)"
            },
            {
                "term": "F",
                "trans": "comme fas (le cheval)"
            },
            {
                "term": "G",
                "trans": "comme gite (l'œil)"
            }
        ],
        "Alphabet et Sons (Partie 3)": [
            {
                "term": "Ɠ",
                "trans": "comme ɠeel (voir) (*Injective vélaire (U+029B).*)"
            },
            {
                "term": "H",
                "trans": "comme o hiid (l'année)"
            },
            {
                "term": "I",
                "trans": "comme in (nous)"
            },
            {
                "term": "J",
                "trans": "comme o jan (le soleil)"
            },
            {
                "term": "K",
                "trans": "comme kor (l'homme)"
            }
        ],
        "Alphabet et Sons (Partie 4)": [
            {
                "term": "L",
                "trans": "comme loxo (la main)"
            },
            {
                "term": "M",
                "trans": "comme maama (grand-parent)"
            },
            {
                "term": "N",
                "trans": "comme nak (la vache)"
            },
            {
                "term": "Ñ",
                "trans": "comme ñuxe (le haricot)"
            },
            {
                "term": "Ŋ",
                "trans": "comme ŋar (venir)"
            }
        ],
        "Alphabet et Sons (Partie 5)": [
            {
                "term": "O",
                "trans": "comme o-yal (le maître)"
            },
            {
                "term": "P",
                "trans": "comme pal (le pont)"
            },
            {
                "term": "Ƥ",
                "trans": "comme ƥada (attendre) (*Injective (U+01A5).*)"
            },
            {
                "term": "Q",
                "trans": "comme qol (le champ)"
            },
            {
                "term": "R",
                "trans": "comme ret (partir)"
            }
        ],
        "Alphabet et Sons (Partie 6)": [
            {
                "term": "S",
                "trans": "comme saare (la maison)"
            },
            {
                "term": "T",
                "trans": "comme tid (fermer)"
            },
            {
                "term": "Ƭ",
                "trans": "comme ƭuf (cracher) (*Injective (U+01AD).*)"
            },
            {
                "term": "U",
                "trans": "comme un (piler)"
            },
            {
                "term": "W",
                "trans": "comme weec (changer)"
            }
        ],
        "Alphabet et Sons (Partie 7)": [
            {
                "term": "X",
                "trans": "comme xal (penser)"
            },
            {
                "term": "Y",
                "trans": "comme yong (passer la journée)"
            },
            {
                "term": "X",
                "trans": "comme xal (penser)"
            },
            {
                "term": "Y",
                "trans": "comme yong (passer la journée)"
            },
            {
                "term": "X",
                "trans": "comme xal (penser)"
            }
        ],
        "Pronoms d'Emphase (Partie 1)": [
            {
                "term": "mi'",
                "trans": "moi"
            },
            {
                "term": "wo'",
                "trans": "toi"
            },
            {
                "term": "ten",
                "trans": "lui / elle"
            },
            {
                "term": "in(o)",
                "trans": "nous"
            },
            {
                "term": "nuun",
                "trans": "vous"
            }
        ],
        "Pronoms d'Emphase (Partie 2)": [
            {
                "term": "den(o)",
                "trans": "eux / elles"
            },
            {
                "term": "den(o)",
                "trans": "eux / elles"
            },
            {
                "term": "den(o)",
                "trans": "eux / elles"
            },
            {
                "term": "den(o)",
                "trans": "eux / elles"
            },
            {
                "term": "den(o)",
                "trans": "eux / elles"
            }
        ],
        "Base Conjugaison (Verbe boug)": [
            {
                "term": "bougam",
                "trans": "j'aime / je veux"
            },
            {
                "term": "bougo",
                "trans": "tu aimes / tu veux"
            },
            {
                "term": "bougu",
                "trans": "il/elle aime / il/elle veut"
            },
            {
                "term": "bougin",
                "trans": "nous aimons / nous voulons"
            },
            {
                "term": "bougam",
                "trans": "j'aime / je veux"
            }
        ]
    },
    "diola": {
        "Alphabet et Prononciation (Partie 1)": [
            {
                "term": "A",
                "trans": "comme Alolo (Bouteille)"
            },
            {
                "term": "B",
                "trans": "comme Bakand (Baignoire)"
            },
            {
                "term": "C",
                "trans": "comme Ceeb (Riz)"
            },
            {
                "term": "D",
                "trans": "comme Daara (École)"
            },
            {
                "term": "E",
                "trans": "comme E-konk (Manguier)"
            }
        ],
        "Alphabet et Prononciation (Partie 2)": [
            {
                "term": "F",
                "trans": "comme Fof (Ici)"
            },
            {
                "term": "G",
                "trans": "comme Gami (Toi)"
            },
            {
                "term": "H",
                "trans": "comme Habat"
            },
            {
                "term": "I",
                "trans": "comme Inji (Moi)"
            },
            {
                "term": "J",
                "trans": "comme Jamm"
            }
        ],
        "Alphabet et Prononciation (Partie 3)": [
            {
                "term": "K",
                "trans": "comme Kaar"
            },
            {
                "term": "L",
                "trans": "comme Loxo"
            },
            {
                "term": "M",
                "trans": "comme Maama"
            },
            {
                "term": "N",
                "trans": "comme Neddo"
            },
            {
                "term": "Ñ",
                "trans": "comme Ñari (*Nasale palatale.*)"
            }
        ],
        "Alphabet et Prononciation (Partie 4)": [
            {
                "term": "Ŋ",
                "trans": "comme Ŋari (*Nasale vélaire.*)"
            },
            {
                "term": "O",
                "trans": "comme Oto"
            },
            {
                "term": "P",
                "trans": "comme Pom"
            },
            {
                "term": "R",
                "trans": "comme Raw"
            },
            {
                "term": "S",
                "trans": "comme Samba"
            }
        ],
        "Alphabet et Prononciation (Partie 5)": [
            {
                "term": "T",
                "trans": "comme Tata"
            },
            {
                "term": "U",
                "trans": "comme Urus"
            },
            {
                "term": "W",
                "trans": "comme Wanag"
            },
            {
                "term": "X",
                "trans": "comme Xar"
            },
            {
                "term": "Y",
                "trans": "comme Yapp"
            }
        ],
        "Pronoms de base": [
            {
                "term": "inji",
                "trans": "je / moi"
            },
            {
                "term": "itche",
                "trans": "tu / toi"
            },
            {
                "term": "anigeb",
                "trans": "il / elle"
            },
            {
                "term": "oli",
                "trans": "nous"
            },
            {
                "term": "inji",
                "trans": "je / moi"
            }
        ],
        "Classes Nominales": [
            {
                "term": "a- (singulier humain)",
                "trans": "ex:a-ɲɩɩl (l'enfant)"
            },
            {
                "term": "ba- (pluriel humain)",
                "trans": "ex:ba-ɲɩɩl (les enfants)"
            },
            {
                "term": "ɛ- (singulier général)",
                "trans": "ex:ɛ-ɲaab (l'éléphant)"
            },
            {
                "term": "sɩ- (pluriel général)",
                "trans": "ex:sɩ-ɲaab (les éléphants)"
            },
            {
                "term": "a- (singulier humain)",
                "trans": "ex:a-ɲɩɩl (l'enfant)"
            }
        ],
        "Alphabet et Prononciation (Partie 1) (Suite 1)": [
            {
                "term": "A",
                "trans": "comme Alolo (Bouteille)"
            },
            {
                "term": "B",
                "trans": "comme Bakand (Baignoire)"
            },
            {
                "term": "C",
                "trans": "comme Ceeb (Riz)"
            },
            {
                "term": "D",
                "trans": "comme Daara (École)"
            },
            {
                "term": "E",
                "trans": "comme E-konk (Manguier)"
            }
        ],
        "Alphabet et Prononciation (Partie 2) (Suite 1)": [
            {
                "term": "F",
                "trans": "comme Fof (Ici)"
            },
            {
                "term": "G",
                "trans": "comme Gami (Toi)"
            },
            {
                "term": "H",
                "trans": "comme Habat"
            },
            {
                "term": "I",
                "trans": "comme Inji (Moi)"
            },
            {
                "term": "J",
                "trans": "comme Jamm"
            }
        ],
        "Alphabet et Prononciation (Partie 3) (Suite 1)": [
            {
                "term": "K",
                "trans": "comme Kaar"
            },
            {
                "term": "L",
                "trans": "comme Loxo"
            },
            {
                "term": "M",
                "trans": "comme Maama"
            },
            {
                "term": "N",
                "trans": "comme Neddo"
            },
            {
                "term": "Ñ",
                "trans": "comme Ñari (*Nasale palatale.*)"
            }
        ]
    },
    "pulaar": {
        "Alphabet et Phonétique (Partie 1)": [
            {
                "term": "A",
                "trans": "comme Al-Kuraan (Le Coran)"
            },
            {
                "term": "B",
                "trans": "comme Baaba (Papa)"
            },
            {
                "term": "Ɓ",
                "trans": "comme Ɓiɗɗo (Enfant) (*Consonne implosive (U+0253).*)"
            },
            {
                "term": "C",
                "trans": "comme Cekiri (Petit pilon)"
            },
            {
                "term": "D",
                "trans": "comme Dada (Maman)"
            }
        ],
        "Alphabet et Phonétique (Partie 2)": [
            {
                "term": "Ɗ",
                "trans": "comme Ɗemngal (Langue) (*Consonne implosive (U+0257).*)"
            },
            {
                "term": "E",
                "trans": "comme Ele (Ici)"
            },
            {
                "term": "F",
                "trans": "comme Fayda (Dignité)"
            },
            {
                "term": "G",
                "trans": "comme Gite (Yeux)"
            },
            {
                "term": "H",
                "trans": "comme Haala (Parole)"
            }
        ],
        "Alphabet et Phonétique (Partie 3)": [
            {
                "term": "I",
                "trans": "comme Ina (Être/Là)"
            },
            {
                "term": "J",
                "trans": "comme Jamma (Nuit)"
            },
            {
                "term": "K",
                "trans": "comme Kaalis (Argent)"
            },
            {
                "term": "L",
                "trans": "comme Lalla (Laver)"
            },
            {
                "term": "M",
                "trans": "comme Maama (Grand-parent)"
            }
        ],
        "Alphabet et Phonétique (Partie 4)": [
            {
                "term": "N",
                "trans": "comme Neddo (Personne)"
            },
            {
                "term": "Ñ",
                "trans": "comme Ñari (Chat) (*Nasale palatale.*)"
            },
            {
                "term": "Ŋ",
                "trans": "comme Ŋari (Beauté) (*Nasale vélaire.*)"
            },
            {
                "term": "O",
                "trans": "comme Omo (Lui/Elle)"
            },
            {
                "term": "P",
                "trans": "comme Pulaar"
            }
        ],
        "Alphabet et Phonétique (Partie 5)": [
            {
                "term": "R",
                "trans": "comme Rawdu (Chien)"
            },
            {
                "term": "S",
                "trans": "comme Safal (Chauffer)"
            },
            {
                "term": "T",
                "trans": "comme Tata (Maman - respectueux)"
            },
            {
                "term": "U",
                "trans": "comme Urus (Or)"
            },
            {
                "term": "W",
                "trans": "comme Wor (Trahir)"
            }
        ],
        "Alphabet et Phonétique (Partie 6)": [
            {
                "term": "X",
                "trans": "comme Xuloo (Dispute)"
            },
            {
                "term": "Y",
                "trans": "comme Yaati (Vraiment)"
            },
            {
                "term": "Ƴ",
                "trans": "comme Ƴiye (Os) (*Consonne glottalisée (U+01B4).*)"
            },
            {
                "term": "'",
                "trans": "comme 'Ena (*Coup de glotte.*)"
            },
            {
                "term": "X",
                "trans": "comme Xuloo (Dispute)"
            }
        ],
        "Pronoms Personnels (Partie 1)": [
            {
                "term": "mi / miɗo",
                "trans": "je / je suis en train de"
            },
            {
                "term": "a / aɗa",
                "trans": "tu / tu es en train de"
            },
            {
                "term": "o / omo",
                "trans": "il/elle / il/elle est en train de"
            },
            {
                "term": "en / eɗen",
                "trans": "nous (inclusif)"
            },
            {
                "term": "min / miɗen",
                "trans": "nous (exclusif)"
            }
        ],
        "Pronoms Personnels (Partie 2)": [
            {
                "term": "on / ono",
                "trans": "vous"
            },
            {
                "term": "ɓe / eɓe",
                "trans": "ils/elles"
            },
            {
                "term": "on / ono",
                "trans": "vous"
            },
            {
                "term": "ɓe / eɓe",
                "trans": "ils/elles"
            },
            {
                "term": "on / ono",
                "trans": "vous"
            }
        ],
        "Base Conjugaison": [
            {
                "term": "mi yahi",
                "trans": "je suis allé"
            },
            {
                "term": "o yahi",
                "trans": "il/elle est allé(e)"
            },
            {
                "term": "en njahii",
                "trans": "nous sommes allés"
            },
            {
                "term": "mi yahi",
                "trans": "je suis allé"
            },
            {
                "term": "o yahi",
                "trans": "il/elle est allé(e)"
            }
        ],
        "Alphabet et Phonétique (Partie 1) (Suite 1)": [
            {
                "term": "A",
                "trans": "comme Al-Kuraan (Le Coran)"
            },
            {
                "term": "B",
                "trans": "comme Baaba (Papa)"
            },
            {
                "term": "Ɓ",
                "trans": "comme Ɓiɗɗo (Enfant) (*Consonne implosive (U+0253).*)"
            },
            {
                "term": "C",
                "trans": "comme Cekiri (Petit pilon)"
            },
            {
                "term": "D",
                "trans": "comme Dada (Maman)"
            }
        ]
    },
    "soninke": {
        "Lettres et Sons (Partie 1)": [
            {
                "term": "A",
                "trans": "comme Áraba (Mercredi)"
            },
            {
                "term": "B",
                "trans": "comme Bátè (Parole)"
            },
            {
                "term": "C",
                "trans": "comme Ceeb (Riz)"
            },
            {
                "term": "D",
                "trans": "comme Dágá (Marmite)"
            },
            {
                "term": "E",
                "trans": "comme Emmanuel"
            }
        ],
        "Lettres et Sons (Partie 2)": [
            {
                "term": "F",
                "trans": "comme Faj (Soigner)"
            },
            {
                "term": "G",
                "trans": "comme Gìllè (Yeux)"
            },
            {
                "term": "H",
                "trans": "comme Haala"
            },
            {
                "term": "I",
                "trans": "comme Idjig"
            },
            {
                "term": "J",
                "trans": "comme Jamm"
            }
        ],
        "Lettres et Sons (Partie 3)": [
            {
                "term": "K",
                "trans": "comme Karat"
            },
            {
                "term": "L",
                "trans": "comme Loxo"
            },
            {
                "term": "M",
                "trans": "comme Mburu"
            },
            {
                "term": "N",
                "trans": "comme Ndox"
            },
            {
                "term": "Ñ",
                "trans": "comme Ñànmè (Manger) (*Le son 'gn'.*)"
            }
        ],
        "Lettres et Sons (Partie 4)": [
            {
                "term": "Ŋ",
                "trans": "comme Ŋàllè (Rire) (*Le son 'ng'.*)"
            },
            {
                "term": "O",
                "trans": "comme Oto"
            },
            {
                "term": "P",
                "trans": "comme Pom"
            },
            {
                "term": "Q",
                "trans": "comme Qarit"
            },
            {
                "term": "R",
                "trans": "comme Reer"
            }
        ],
        "Lettres et Sons (Partie 5)": [
            {
                "term": "S",
                "trans": "comme Safara"
            },
            {
                "term": "T",
                "trans": "comme Tank"
            },
            {
                "term": "U",
                "trans": "comme Urus"
            },
            {
                "term": "W",
                "trans": "comme Wanag"
            },
            {
                "term": "X",
                "trans": "comme Xar"
            }
        ],
        "Lettres et Sons (Partie 6)": [
            {
                "term": "Y",
                "trans": "comme Yapp"
            },
            {
                "term": "Y",
                "trans": "comme Yapp"
            },
            {
                "term": "Y",
                "trans": "comme Yapp"
            },
            {
                "term": "Y",
                "trans": "comme Yapp"
            },
            {
                "term": "Y",
                "trans": "comme Yapp"
            }
        ],
        "Pronoms Sujets": [
            {
                "term": "ńké",
                "trans": "je / moi"
            },
            {
                "term": "ánké",
                "trans": "tu / toi"
            },
            {
                "term": "àké",
                "trans": "il / elle"
            },
            {
                "term": "ókú",
                "trans": "nous"
            },
            {
                "term": "áxákù",
                "trans": "vous"
            }
        ],
        "Lettres et Sons (Partie 1) (Suite 1)": [
            {
                "term": "A",
                "trans": "comme Áraba (Mercredi)"
            },
            {
                "term": "B",
                "trans": "comme Bátè (Parole)"
            },
            {
                "term": "C",
                "trans": "comme Ceeb (Riz)"
            },
            {
                "term": "D",
                "trans": "comme Dágá (Marmite)"
            },
            {
                "term": "E",
                "trans": "comme Emmanuel"
            }
        ],
        "Lettres et Sons (Partie 2) (Suite 1)": [
            {
                "term": "F",
                "trans": "comme Faj (Soigner)"
            },
            {
                "term": "G",
                "trans": "comme Gìllè (Yeux)"
            },
            {
                "term": "H",
                "trans": "comme Haala"
            },
            {
                "term": "I",
                "trans": "comme Idjig"
            },
            {
                "term": "J",
                "trans": "comme Jamm"
            }
        ],
        "Lettres et Sons (Partie 3) (Suite 1)": [
            {
                "term": "K",
                "trans": "comme Karat"
            },
            {
                "term": "L",
                "trans": "comme Loxo"
            },
            {
                "term": "M",
                "trans": "comme Mburu"
            },
            {
                "term": "N",
                "trans": "comme Ndox"
            },
            {
                "term": "Ñ",
                "trans": "comme Ñànmè (Manger) (*Le son 'gn'.*)"
            }
        ]
    },
    "bambara": {},
    "mandinka": {
        "Alphabet Mandinka (Partie 1)": [
            {
                "term": "A",
                "trans": "comme Abada (Jamais)"
            },
            {
                "term": "B",
                "trans": "comme Baluo (Vie)"
            },
            {
                "term": "C",
                "trans": "comme Ceeb"
            },
            {
                "term": "D",
                "trans": "comme Da (Bouche)"
            },
            {
                "term": "E",
                "trans": "comme Ele (Toi)"
            }
        ],
        "Alphabet Mandinka (Partie 2)": [
            {
                "term": "F",
                "trans": "comme Fa (Père)"
            },
            {
                "term": "G",
                "trans": "comme Gelo (Glace)"
            },
            {
                "term": "H",
                "trans": "comme Hakilo (Esprit)"
            },
            {
                "term": "I",
                "trans": "comme Ina"
            },
            {
                "term": "J",
                "trans": "comme Jamm"
            }
        ],
        "Alphabet Mandinka (Partie 3)": [
            {
                "term": "K",
                "trans": "comme Kaar"
            },
            {
                "term": "L",
                "trans": "comme Loxo"
            },
            {
                "term": "M",
                "trans": "comme Maama"
            },
            {
                "term": "N",
                "trans": "comme Neddo"
            },
            {
                "term": "Ñ",
                "trans": "comme Ñari"
            }
        ],
        "Alphabet Mandinka (Partie 4)": [
            {
                "term": "Ŋ",
                "trans": "comme Ŋari"
            },
            {
                "term": "O",
                "trans": "comme Oto"
            },
            {
                "term": "P",
                "trans": "comme Pom"
            },
            {
                "term": "R",
                "trans": "comme Raw"
            },
            {
                "term": "S",
                "trans": "comme Samba"
            }
        ],
        "Alphabet Mandinka (Partie 5)": [
            {
                "term": "T",
                "trans": "comme Tata"
            },
            {
                "term": "U",
                "trans": "comme Urus"
            },
            {
                "term": "W",
                "trans": "comme Wanag"
            },
            {
                "term": "X",
                "trans": "comme Xar"
            },
            {
                "term": "Y",
                "trans": "comme Yapp"
            }
        ],
        "Pronoms et Particules (Partie 1)": [
            {
                "term": "n",
                "trans": "je"
            },
            {
                "term": "i",
                "trans": "tu"
            },
            {
                "term": "a",
                "trans": "il / elle"
            },
            {
                "term": "n'tolu",
                "trans": "nous"
            },
            {
                "term": "al'tolu",
                "trans": "vous"
            }
        ],
        "Pronoms et Particules (Partie 2)": [
            {
                "term": "i'tolu",
                "trans": "ils / elles"
            },
            {
                "term": "i'tolu",
                "trans": "ils / elles"
            },
            {
                "term": "i'tolu",
                "trans": "ils / elles"
            },
            {
                "term": "i'tolu",
                "trans": "ils / elles"
            },
            {
                "term": "i'tolu",
                "trans": "ils / elles"
            }
        ],
        "Alphabet Mandinka (Partie 1) (Suite 1)": [
            {
                "term": "A",
                "trans": "comme Abada (Jamais)"
            },
            {
                "term": "B",
                "trans": "comme Baluo (Vie)"
            },
            {
                "term": "C",
                "trans": "comme Ceeb"
            },
            {
                "term": "D",
                "trans": "comme Da (Bouche)"
            },
            {
                "term": "E",
                "trans": "comme Ele (Toi)"
            }
        ],
        "Alphabet Mandinka (Partie 2) (Suite 1)": [
            {
                "term": "F",
                "trans": "comme Fa (Père)"
            },
            {
                "term": "G",
                "trans": "comme Gelo (Glace)"
            },
            {
                "term": "H",
                "trans": "comme Hakilo (Esprit)"
            },
            {
                "term": "I",
                "trans": "comme Ina"
            },
            {
                "term": "J",
                "trans": "comme Jamm"
            }
        ],
        "Alphabet Mandinka (Partie 3) (Suite 1)": [
            {
                "term": "K",
                "trans": "comme Kaar"
            },
            {
                "term": "L",
                "trans": "comme Loxo"
            },
            {
                "term": "M",
                "trans": "comme Maama"
            },
            {
                "term": "N",
                "trans": "comme Neddo"
            },
            {
                "term": "Ñ",
                "trans": "comme Ñari"
            }
        ]
    },
    "manjak": {
        "Phonétique Manjak": [
            {
                "term": "A",
                "trans": "comme a-ñ (le soleil)"
            },
            {
                "term": "B",
                "trans": "comme b-uk (manger)"
            },
            {
                "term": "D",
                "trans": "comme d-ap (viande)"
            },
            {
                "term": "A",
                "trans": "comme a-ñ (le soleil)"
            },
            {
                "term": "B",
                "trans": "comme b-uk (manger)"
            }
        ],
        "Pronoms": [
            {
                "term": "idju",
                "trans": "je"
            },
            {
                "term": "itse",
                "trans": "tu"
            },
            {
                "term": "idju",
                "trans": "je"
            },
            {
                "term": "itse",
                "trans": "tu"
            },
            {
                "term": "idju",
                "trans": "je"
            }
        ],
        "Phonétique Manjak (Suite 1)": [
            {
                "term": "A",
                "trans": "comme a-ñ (le soleil)"
            },
            {
                "term": "B",
                "trans": "comme b-uk (manger)"
            },
            {
                "term": "D",
                "trans": "comme d-ap (viande)"
            },
            {
                "term": "A",
                "trans": "comme a-ñ (le soleil)"
            },
            {
                "term": "B",
                "trans": "comme b-uk (manger)"
            }
        ],
        "Pronoms (Suite 1)": [
            {
                "term": "idju",
                "trans": "je"
            },
            {
                "term": "itse",
                "trans": "tu"
            },
            {
                "term": "idju",
                "trans": "je"
            },
            {
                "term": "itse",
                "trans": "tu"
            },
            {
                "term": "idju",
                "trans": "je"
            }
        ],
        "Phonétique Manjak (Suite 2)": [
            {
                "term": "A",
                "trans": "comme a-ñ (le soleil)"
            },
            {
                "term": "B",
                "trans": "comme b-uk (manger)"
            },
            {
                "term": "D",
                "trans": "comme d-ap (viande)"
            },
            {
                "term": "A",
                "trans": "comme a-ñ (le soleil)"
            },
            {
                "term": "B",
                "trans": "comme b-uk (manger)"
            }
        ],
        "Pronoms (Suite 2)": [
            {
                "term": "idju",
                "trans": "je"
            },
            {
                "term": "itse",
                "trans": "tu"
            },
            {
                "term": "idju",
                "trans": "je"
            },
            {
                "term": "itse",
                "trans": "tu"
            },
            {
                "term": "idju",
                "trans": "je"
            }
        ],
        "Phonétique Manjak (Suite 3)": [
            {
                "term": "A",
                "trans": "comme a-ñ (le soleil)"
            },
            {
                "term": "B",
                "trans": "comme b-uk (manger)"
            },
            {
                "term": "D",
                "trans": "comme d-ap (viande)"
            },
            {
                "term": "A",
                "trans": "comme a-ñ (le soleil)"
            },
            {
                "term": "B",
                "trans": "comme b-uk (manger)"
            }
        ],
        "Pronoms (Suite 3)": [
            {
                "term": "idju",
                "trans": "je"
            },
            {
                "term": "itse",
                "trans": "tu"
            },
            {
                "term": "idju",
                "trans": "je"
            },
            {
                "term": "itse",
                "trans": "tu"
            },
            {
                "term": "idju",
                "trans": "je"
            }
        ],
        "Phonétique Manjak (Suite 4)": [
            {
                "term": "A",
                "trans": "comme a-ñ (le soleil)"
            },
            {
                "term": "B",
                "trans": "comme b-uk (manger)"
            },
            {
                "term": "D",
                "trans": "comme d-ap (viande)"
            },
            {
                "term": "A",
                "trans": "comme a-ñ (le soleil)"
            },
            {
                "term": "B",
                "trans": "comme b-uk (manger)"
            }
        ],
        "Pronoms (Suite 4)": [
            {
                "term": "idju",
                "trans": "je"
            },
            {
                "term": "itse",
                "trans": "tu"
            },
            {
                "term": "idju",
                "trans": "je"
            },
            {
                "term": "itse",
                "trans": "tu"
            },
            {
                "term": "idju",
                "trans": "je"
            }
        ]
    },
    "balante": {
        "Alphabet Balante (Partie 1)": [
            {
                "term": "A",
                "trans": "comme Abe (Bonjour)"
            },
            {
                "term": "B",
                "trans": "comme Bi (Aujourd'hui)"
            },
            {
                "term": "D",
                "trans": "comme Deye (Comment)"
            },
            {
                "term": "E",
                "trans": "comme Ele (Cela)"
            },
            {
                "term": "F",
                "trans": "comme Fala (Parler)"
            }
        ],
        "Alphabet Balante (Partie 2)": [
            {
                "term": "Ŧ",
                "trans": "comme ŧan (Faire)"
            },
            {
                "term": "Ŧ",
                "trans": "comme ŧan (Faire)"
            },
            {
                "term": "Ŧ",
                "trans": "comme ŧan (Faire)"
            },
            {
                "term": "Ŧ",
                "trans": "comme ŧan (Faire)"
            },
            {
                "term": "Ŧ",
                "trans": "comme ŧan (Faire)"
            }
        ],
        "Pronoms de base": [
            {
                "term": "n",
                "trans": "je"
            },
            {
                "term": "i",
                "trans": "tu"
            },
            {
                "term": "n",
                "trans": "je"
            },
            {
                "term": "i",
                "trans": "tu"
            },
            {
                "term": "n",
                "trans": "je"
            }
        ],
        "Salutations de base": [
            {
                "term": "abe",
                "trans": "Bonjour"
            },
            {
                "term": "ndeye",
                "trans": "Comment ça va ?"
            },
            {
                "term": "abe",
                "trans": "Bonjour"
            },
            {
                "term": "ndeye",
                "trans": "Comment ça va ?"
            },
            {
                "term": "abe",
                "trans": "Bonjour"
            }
        ],
        "Alphabet Balante (Partie 1) (Suite 1)": [
            {
                "term": "A",
                "trans": "comme Abe (Bonjour)"
            },
            {
                "term": "B",
                "trans": "comme Bi (Aujourd'hui)"
            },
            {
                "term": "D",
                "trans": "comme Deye (Comment)"
            },
            {
                "term": "E",
                "trans": "comme Ele (Cela)"
            },
            {
                "term": "F",
                "trans": "comme Fala (Parler)"
            }
        ],
        "Alphabet Balante (Partie 2) (Suite 1)": [
            {
                "term": "Ŧ",
                "trans": "comme ŧan (Faire)"
            },
            {
                "term": "Ŧ",
                "trans": "comme ŧan (Faire)"
            },
            {
                "term": "Ŧ",
                "trans": "comme ŧan (Faire)"
            },
            {
                "term": "Ŧ",
                "trans": "comme ŧan (Faire)"
            },
            {
                "term": "Ŧ",
                "trans": "comme ŧan (Faire)"
            }
        ],
        "Pronoms de base (Suite 1)": [
            {
                "term": "n",
                "trans": "je"
            },
            {
                "term": "i",
                "trans": "tu"
            },
            {
                "term": "n",
                "trans": "je"
            },
            {
                "term": "i",
                "trans": "tu"
            },
            {
                "term": "n",
                "trans": "je"
            }
        ],
        "Salutations de base (Suite 1)": [
            {
                "term": "abe",
                "trans": "Bonjour"
            },
            {
                "term": "ndeye",
                "trans": "Comment ça va ?"
            },
            {
                "term": "abe",
                "trans": "Bonjour"
            },
            {
                "term": "ndeye",
                "trans": "Comment ça va ?"
            },
            {
                "term": "abe",
                "trans": "Bonjour"
            }
        ],
        "Alphabet Balante (Partie 1) (Suite 2)": [
            {
                "term": "A",
                "trans": "comme Abe (Bonjour)"
            },
            {
                "term": "B",
                "trans": "comme Bi (Aujourd'hui)"
            },
            {
                "term": "D",
                "trans": "comme Deye (Comment)"
            },
            {
                "term": "E",
                "trans": "comme Ele (Cela)"
            },
            {
                "term": "F",
                "trans": "comme Fala (Parler)"
            }
        ],
        "Alphabet Balante (Partie 2) (Suite 2)": [
            {
                "term": "Ŧ",
                "trans": "comme ŧan (Faire)"
            },
            {
                "term": "Ŧ",
                "trans": "comme ŧan (Faire)"
            },
            {
                "term": "Ŧ",
                "trans": "comme ŧan (Faire)"
            },
            {
                "term": "Ŧ",
                "trans": "comme ŧan (Faire)"
            },
            {
                "term": "Ŧ",
                "trans": "comme ŧan (Faire)"
            }
        ]
    },
    "mankagne": {
        "Alphabet Phonétique": [
            {
                "term": "A",
                "trans": "comme a-pëñ (le chien)"
            },
            {
                "term": "B",
                "trans": "comme b-ët (l'oeil)"
            },
            {
                "term": "D",
                "trans": "comme d-ak (la tête)"
            },
            {
                "term": "A",
                "trans": "comme a-pëñ (le chien)"
            },
            {
                "term": "B",
                "trans": "comme b-ët (l'oeil)"
            }
        ],
        "Pronoms": [
            {
                "term": "idje",
                "trans": "je"
            },
            {
                "term": "itse",
                "trans": "tu"
            },
            {
                "term": "idje",
                "trans": "je"
            },
            {
                "term": "itse",
                "trans": "tu"
            },
            {
                "term": "idje",
                "trans": "je"
            }
        ],
        "Alphabet Phonétique (Suite 1)": [
            {
                "term": "A",
                "trans": "comme a-pëñ (le chien)"
            },
            {
                "term": "B",
                "trans": "comme b-ët (l'oeil)"
            },
            {
                "term": "D",
                "trans": "comme d-ak (la tête)"
            },
            {
                "term": "A",
                "trans": "comme a-pëñ (le chien)"
            },
            {
                "term": "B",
                "trans": "comme b-ët (l'oeil)"
            }
        ],
        "Pronoms (Suite 1)": [
            {
                "term": "idje",
                "trans": "je"
            },
            {
                "term": "itse",
                "trans": "tu"
            },
            {
                "term": "idje",
                "trans": "je"
            },
            {
                "term": "itse",
                "trans": "tu"
            },
            {
                "term": "idje",
                "trans": "je"
            }
        ],
        "Alphabet Phonétique (Suite 2)": [
            {
                "term": "A",
                "trans": "comme a-pëñ (le chien)"
            },
            {
                "term": "B",
                "trans": "comme b-ët (l'oeil)"
            },
            {
                "term": "D",
                "trans": "comme d-ak (la tête)"
            },
            {
                "term": "A",
                "trans": "comme a-pëñ (le chien)"
            },
            {
                "term": "B",
                "trans": "comme b-ët (l'oeil)"
            }
        ],
        "Pronoms (Suite 2)": [
            {
                "term": "idje",
                "trans": "je"
            },
            {
                "term": "itse",
                "trans": "tu"
            },
            {
                "term": "idje",
                "trans": "je"
            },
            {
                "term": "itse",
                "trans": "tu"
            },
            {
                "term": "idje",
                "trans": "je"
            }
        ],
        "Alphabet Phonétique (Suite 3)": [
            {
                "term": "A",
                "trans": "comme a-pëñ (le chien)"
            },
            {
                "term": "B",
                "trans": "comme b-ët (l'oeil)"
            },
            {
                "term": "D",
                "trans": "comme d-ak (la tête)"
            },
            {
                "term": "A",
                "trans": "comme a-pëñ (le chien)"
            },
            {
                "term": "B",
                "trans": "comme b-ët (l'oeil)"
            }
        ],
        "Pronoms (Suite 3)": [
            {
                "term": "idje",
                "trans": "je"
            },
            {
                "term": "itse",
                "trans": "tu"
            },
            {
                "term": "idje",
                "trans": "je"
            },
            {
                "term": "itse",
                "trans": "tu"
            },
            {
                "term": "idje",
                "trans": "je"
            }
        ],
        "Alphabet Phonétique (Suite 4)": [
            {
                "term": "A",
                "trans": "comme a-pëñ (le chien)"
            },
            {
                "term": "B",
                "trans": "comme b-ët (l'oeil)"
            },
            {
                "term": "D",
                "trans": "comme d-ak (la tête)"
            },
            {
                "term": "A",
                "trans": "comme a-pëñ (le chien)"
            },
            {
                "term": "B",
                "trans": "comme b-ët (l'oeil)"
            }
        ],
        "Pronoms (Suite 4)": [
            {
                "term": "idje",
                "trans": "je"
            },
            {
                "term": "itse",
                "trans": "tu"
            },
            {
                "term": "idje",
                "trans": "je"
            },
            {
                "term": "itse",
                "trans": "tu"
            },
            {
                "term": "idje",
                "trans": "je"
            }
        ]
    },
    "bainouk": {
        "Alphabet et TIC (Partie 1)": [
            {
                "term": "A",
                "trans": "comme Aas (Visage)"
            },
            {
                "term": "B",
                "trans": "comme Bukat (Marcher)"
            },
            {
                "term": "D",
                "trans": "comme Dox (Aller)"
            },
            {
                "term": "E",
                "trans": "comme E-ñen (Main)"
            },
            {
                "term": "Ë",
                "trans": "comme Kër (Maison)"
            }
        ],
        "Alphabet et TIC (Partie 2)": [
            {
                "term": "Ŧ",
                "trans": "comme ŧubal (Pluie)"
            },
            {
                "term": "Ţ",
                "trans": "comme ţax (Terre)"
            },
            {
                "term": "Ŧ",
                "trans": "comme ŧubal (Pluie)"
            },
            {
                "term": "Ţ",
                "trans": "comme ţax (Terre)"
            },
            {
                "term": "Ŧ",
                "trans": "comme ŧubal (Pluie)"
            }
        ],
        "Pronoms": [
            {
                "term": "idun",
                "trans": "je"
            },
            {
                "term": "iya",
                "trans": "tu"
            },
            {
                "term": "ino",
                "trans": "il/elle"
            },
            {
                "term": "idun",
                "trans": "je"
            },
            {
                "term": "iya",
                "trans": "tu"
            }
        ],
        "Alphabet et Classes": [
            {
                "term": "ka-ñen",
                "trans": "la main (classe KA)"
            },
            {
                "term": "u-†ubal",
                "trans": "la pluie (classe U)"
            },
            {
                "term": "b-ko",
                "trans": "l'arbre (classe B)"
            },
            {
                "term": "ka-ñen",
                "trans": "la main (classe KA)"
            },
            {
                "term": "u-†ubal",
                "trans": "la pluie (classe U)"
            }
        ],
        "Alphabet et TIC (Partie 1) (Suite 1)": [
            {
                "term": "A",
                "trans": "comme Aas (Visage)"
            },
            {
                "term": "B",
                "trans": "comme Bukat (Marcher)"
            },
            {
                "term": "D",
                "trans": "comme Dox (Aller)"
            },
            {
                "term": "E",
                "trans": "comme E-ñen (Main)"
            },
            {
                "term": "Ë",
                "trans": "comme Kër (Maison)"
            }
        ],
        "Alphabet et TIC (Partie 2) (Suite 1)": [
            {
                "term": "Ŧ",
                "trans": "comme ŧubal (Pluie)"
            },
            {
                "term": "Ţ",
                "trans": "comme ţax (Terre)"
            },
            {
                "term": "Ŧ",
                "trans": "comme ŧubal (Pluie)"
            },
            {
                "term": "Ţ",
                "trans": "comme ţax (Terre)"
            },
            {
                "term": "Ŧ",
                "trans": "comme ŧubal (Pluie)"
            }
        ],
        "Pronoms (Suite 1)": [
            {
                "term": "idun",
                "trans": "je"
            },
            {
                "term": "iya",
                "trans": "tu"
            },
            {
                "term": "ino",
                "trans": "il/elle"
            },
            {
                "term": "idun",
                "trans": "je"
            },
            {
                "term": "iya",
                "trans": "tu"
            }
        ],
        "Alphabet et Classes (Suite 1)": [
            {
                "term": "ka-ñen",
                "trans": "la main (classe KA)"
            },
            {
                "term": "u-†ubal",
                "trans": "la pluie (classe U)"
            },
            {
                "term": "b-ko",
                "trans": "l'arbre (classe B)"
            },
            {
                "term": "ka-ñen",
                "trans": "la main (classe KA)"
            },
            {
                "term": "u-†ubal",
                "trans": "la pluie (classe U)"
            }
        ],
        "Alphabet et TIC (Partie 1) (Suite 2)": [
            {
                "term": "A",
                "trans": "comme Aas (Visage)"
            },
            {
                "term": "B",
                "trans": "comme Bukat (Marcher)"
            },
            {
                "term": "D",
                "trans": "comme Dox (Aller)"
            },
            {
                "term": "E",
                "trans": "comme E-ñen (Main)"
            },
            {
                "term": "Ë",
                "trans": "comme Kër (Maison)"
            }
        ],
        "Alphabet et TIC (Partie 2) (Suite 2)": [
            {
                "term": "Ŧ",
                "trans": "comme ŧubal (Pluie)"
            },
            {
                "term": "Ţ",
                "trans": "comme ţax (Terre)"
            },
            {
                "term": "Ŧ",
                "trans": "comme ŧubal (Pluie)"
            },
            {
                "term": "Ţ",
                "trans": "comme ţax (Terre)"
            },
            {
                "term": "Ŧ",
                "trans": "comme ŧubal (Pluie)"
            }
        ]
    },
    "menik": {
        "Phonétique Ménik": [
            {
                "term": "A",
                "trans": "comme Ay (Vivre)"
            },
            {
                "term": "B",
                "trans": "comme Ɓe (Faire)"
            },
            {
                "term": "E",
                "trans": "comme Èm (Manger)"
            },
            {
                "term": "A",
                "trans": "comme Ay (Vivre)"
            },
            {
                "term": "B",
                "trans": "comme Ɓe (Faire)"
            }
        ],
        "Pronoms": [
            {
                "term": "min",
                "trans": "je"
            },
            {
                "term": "wo",
                "trans": "tu"
            },
            {
                "term": "min",
                "trans": "je"
            },
            {
                "term": "wo",
                "trans": "tu"
            },
            {
                "term": "min",
                "trans": "je"
            }
        ],
        "Phonétique Ménik (Suite 1)": [
            {
                "term": "A",
                "trans": "comme Ay (Vivre)"
            },
            {
                "term": "B",
                "trans": "comme Ɓe (Faire)"
            },
            {
                "term": "E",
                "trans": "comme Èm (Manger)"
            },
            {
                "term": "A",
                "trans": "comme Ay (Vivre)"
            },
            {
                "term": "B",
                "trans": "comme Ɓe (Faire)"
            }
        ],
        "Pronoms (Suite 1)": [
            {
                "term": "min",
                "trans": "je"
            },
            {
                "term": "wo",
                "trans": "tu"
            },
            {
                "term": "min",
                "trans": "je"
            },
            {
                "term": "wo",
                "trans": "tu"
            },
            {
                "term": "min",
                "trans": "je"
            }
        ],
        "Phonétique Ménik (Suite 2)": [
            {
                "term": "A",
                "trans": "comme Ay (Vivre)"
            },
            {
                "term": "B",
                "trans": "comme Ɓe (Faire)"
            },
            {
                "term": "E",
                "trans": "comme Èm (Manger)"
            },
            {
                "term": "A",
                "trans": "comme Ay (Vivre)"
            },
            {
                "term": "B",
                "trans": "comme Ɓe (Faire)"
            }
        ],
        "Pronoms (Suite 2)": [
            {
                "term": "min",
                "trans": "je"
            },
            {
                "term": "wo",
                "trans": "tu"
            },
            {
                "term": "min",
                "trans": "je"
            },
            {
                "term": "wo",
                "trans": "tu"
            },
            {
                "term": "min",
                "trans": "je"
            }
        ],
        "Phonétique Ménik (Suite 3)": [
            {
                "term": "A",
                "trans": "comme Ay (Vivre)"
            },
            {
                "term": "B",
                "trans": "comme Ɓe (Faire)"
            },
            {
                "term": "E",
                "trans": "comme Èm (Manger)"
            },
            {
                "term": "A",
                "trans": "comme Ay (Vivre)"
            },
            {
                "term": "B",
                "trans": "comme Ɓe (Faire)"
            }
        ],
        "Pronoms (Suite 3)": [
            {
                "term": "min",
                "trans": "je"
            },
            {
                "term": "wo",
                "trans": "tu"
            },
            {
                "term": "min",
                "trans": "je"
            },
            {
                "term": "wo",
                "trans": "tu"
            },
            {
                "term": "min",
                "trans": "je"
            }
        ],
        "Phonétique Ménik (Suite 4)": [
            {
                "term": "A",
                "trans": "comme Ay (Vivre)"
            },
            {
                "term": "B",
                "trans": "comme Ɓe (Faire)"
            },
            {
                "term": "E",
                "trans": "comme Èm (Manger)"
            },
            {
                "term": "A",
                "trans": "comme Ay (Vivre)"
            },
            {
                "term": "B",
                "trans": "comme Ɓe (Faire)"
            }
        ],
        "Pronoms (Suite 4)": [
            {
                "term": "min",
                "trans": "je"
            },
            {
                "term": "wo",
                "trans": "tu"
            },
            {
                "term": "min",
                "trans": "je"
            },
            {
                "term": "wo",
                "trans": "tu"
            },
            {
                "term": "min",
                "trans": "je"
            }
        ]
    },
    "hassaniya": {
        "Alphabet et Diacritiques": [
            {
                "term": "A",
                "trans": "comme Änä (Moi)"
            },
            {
                "term": "B",
                "trans": "comme Báid (Blanc)"
            },
            {
                "term": "D",
                "trans": "comme Dár (Maison)"
            },
            {
                "term": "E",
                "trans": "comme Eit (Soleil)"
            },
            {
                "term": "A",
                "trans": "comme Änä (Moi)"
            }
        ],
        "Pronoms": [
            {
                "term": "änä",
                "trans": "je"
            },
            {
                "term": "antä",
                "trans": "tu (m)"
            },
            {
                "term": "anti",
                "trans": "tu (f)"
            },
            {
                "term": "änä",
                "trans": "je"
            },
            {
                "term": "antä",
                "trans": "tu (m)"
            }
        ],
        "Alphabet et Diacritiques (Suite 1)": [
            {
                "term": "A",
                "trans": "comme Änä (Moi)"
            },
            {
                "term": "B",
                "trans": "comme Báid (Blanc)"
            },
            {
                "term": "D",
                "trans": "comme Dár (Maison)"
            },
            {
                "term": "E",
                "trans": "comme Eit (Soleil)"
            },
            {
                "term": "A",
                "trans": "comme Änä (Moi)"
            }
        ],
        "Pronoms (Suite 1)": [
            {
                "term": "änä",
                "trans": "je"
            },
            {
                "term": "antä",
                "trans": "tu (m)"
            },
            {
                "term": "anti",
                "trans": "tu (f)"
            },
            {
                "term": "änä",
                "trans": "je"
            },
            {
                "term": "antä",
                "trans": "tu (m)"
            }
        ],
        "Alphabet et Diacritiques (Suite 2)": [
            {
                "term": "A",
                "trans": "comme Änä (Moi)"
            },
            {
                "term": "B",
                "trans": "comme Báid (Blanc)"
            },
            {
                "term": "D",
                "trans": "comme Dár (Maison)"
            },
            {
                "term": "E",
                "trans": "comme Eit (Soleil)"
            },
            {
                "term": "A",
                "trans": "comme Änä (Moi)"
            }
        ],
        "Pronoms (Suite 2)": [
            {
                "term": "änä",
                "trans": "je"
            },
            {
                "term": "antä",
                "trans": "tu (m)"
            },
            {
                "term": "anti",
                "trans": "tu (f)"
            },
            {
                "term": "änä",
                "trans": "je"
            },
            {
                "term": "antä",
                "trans": "tu (m)"
            }
        ],
        "Alphabet et Diacritiques (Suite 3)": [
            {
                "term": "A",
                "trans": "comme Änä (Moi)"
            },
            {
                "term": "B",
                "trans": "comme Báid (Blanc)"
            },
            {
                "term": "D",
                "trans": "comme Dár (Maison)"
            },
            {
                "term": "E",
                "trans": "comme Eit (Soleil)"
            },
            {
                "term": "A",
                "trans": "comme Änä (Moi)"
            }
        ],
        "Pronoms (Suite 3)": [
            {
                "term": "änä",
                "trans": "je"
            },
            {
                "term": "antä",
                "trans": "tu (m)"
            },
            {
                "term": "anti",
                "trans": "tu (f)"
            },
            {
                "term": "änä",
                "trans": "je"
            },
            {
                "term": "antä",
                "trans": "tu (m)"
            }
        ],
        "Alphabet et Diacritiques (Suite 4)": [
            {
                "term": "A",
                "trans": "comme Änä (Moi)"
            },
            {
                "term": "B",
                "trans": "comme Báid (Blanc)"
            },
            {
                "term": "D",
                "trans": "comme Dár (Maison)"
            },
            {
                "term": "E",
                "trans": "comme Eit (Soleil)"
            },
            {
                "term": "A",
                "trans": "comme Änä (Moi)"
            }
        ],
        "Pronoms (Suite 4)": [
            {
                "term": "änä",
                "trans": "je"
            },
            {
                "term": "antä",
                "trans": "tu (m)"
            },
            {
                "term": "anti",
                "trans": "tu (f)"
            },
            {
                "term": "änä",
                "trans": "je"
            },
            {
                "term": "antä",
                "trans": "tu (m)"
            }
        ]
    }
};
